---
title: "Open peer review of data about the toxicology of pesticedes for bees"
author: "Thijmen van Brenk"
date: "`r Sys.Date()`"
output: bookdown::html_document2
bibliography: "`r rbbt::bbt_write_bib('bibliography/bibliography02.json', overwrite = TRUE)`"
---


in this assignment, this study [@stroblPositiveCorrelationPesticide2020] will be graded on the criteria for reproducibility.  
<br>
<br>


### introduction to this article    
the use of pesticides is one of the main reasons of loss of biodiversity, and the combination of multiple pesticides could even make this worse. in this experiment it is investigated what the sublethal (food consumption) and the lethal (survival) effects of pesticides are on adult female solitary bees, *Osmia bicornis*.       
<br>
to perform these tests, female solitary bees were divided into 4 groups:        
    pesticide free (control)
    herbicide
    pesticide
    combined (both herbicide and pesticide)
their consumption rate and longevity were measured and the data from these two variables are used for analysis.
<br>
<br>
their is no significant difference in survival and consumption between te different groups. there is however a significant positive correlation between the consumption rate and the longevity of these bees.

### grading of this experiment on the transparancy criteria

| transparancy<br>criteria | grading                                        |
|--------------------------|------------------------------------------------|
| study purpose            | TRUE                                           |
| data<br>availability     | FALSE<br>only part of the data is<br>available |
| data <br>location        | at the beginning/<br>at the end                |
| study<br>location        | TRUE<br>materials/methods                      |
| author<br>review         | location and email<br>are present at the top   |
| ethics<br>statement      | FALSE                                          |
| funding<br>statement     | TRUE                                           |
| code<br>availability     | TRUE                                           |

The part of the data that is available can be accessed through this directory: "data/insects-957898-supplementary.xlsx"



